### ISSUE TITLE
Support sub-entries ex: multiple positions within a Company

### ISSUE THREAD

**Issue by jgonzalezm** [JSidrach/resume-yaml#2]
I'm thinking of the case where there are someone has had multiple positions within the same company.  It would be useful to support subentries for sections.
For example:

###Where 1
What 1 - Date 1
Description 1
What 2 - Date 2
Description 2

###Where 2
What 3 - Date 3
Description 3
What 4 - Date 4
Description 4

**Comment by JSidrach** [comment]
This sounds like a useful feature. Let me research different options to implement this and if it is needed to change the yaml input.

**Comment by JSidrach** [comment]
I just implemented a way to do this. Since I wanted to keep the format so this feature does not break previous YAMLs, the way to do this now is to omit the where and location tags in an entry, so it groups with the previous one.
You can see an example in input/example.yaml and its output.
Thanks again for the suggestion!

**Comment by JSidrach** [comment]
(Feel free to comment in this issue even if it is closed if you need to add something else)
